### PR TITLE
Add rubocop support

### PR DESCRIPTION
**Pull request by ShockwaveNN**
Implement #298

### CODE REVIEW

**Comment by andrewsomething** [comment]
@ShockwaveNN This is a great start!  Dropping support for Ruby 2.5 sounds reasonable to me as well.

**Comment by ShockwaveNN** [comment]
@andrewsomething Great, I'll continue to fix issues this week and notify you then I get to some finishing point

**Comment by ShockwaveNN** [comment]
@andrewsomething I think I'm done, for now, I've resolved all easily fixable errors\warnings and probably do not break any parts of the code, all other changes require more precise work so maybe it can be done in the future

**Review by andrewsomething — APPROVED** [review]
:+1:  Great stuff! Thanks for all your work on this @ShockwaveNN!

**Pull request merged**
