### PR TITLE
Document droplet resource’s params in readme file

### PR DESCRIPTION
**Pull request by pawel2105**
It took me a while to find out how to create a new droplet with this gem and include my SSH keys. I thought some documentation may come in handy.

### CODE REVIEW

**Comment by phillbaker** [comment]
@pawel2105 thanks for the PR. Maybe a way to paraphrase this and avoid having to keep this in sync with https://developers.digitalocean.com/ is to reference that page and explain that the mapping is very similar?

**Comment by bobbytables** [comment]
I agree with that. Sorry for the delayed response @pawel2105 too.

**Comment by frizop** [comment]
Oh crap, this totally would have answered another problem I ran into but just figured out yesterday.. Pointing out that the ssh key is an array would have been helpful indeed.

**Comment by nanzhong** [comment]
Sorry as well for the extremely delayed response. https://github.com/digitalocean/droplet_kit/pull/79 was merged, which also addresses this issue and provides a clear example.

I agree with @phillbaker in that it would probably be more ideal to reference the developer docs so that we don't run into problems with docs getting out of sync.

**Pull request closed without merging**
