### PR TITLE
Add support to :page and :per_page query keys in other resources

### PR DESCRIPTION
**Pull request by alambike**
susceptibles to be paged

    - domain
    - domain record
    - region
    - size
    - ssh_key
    - image action

### CODE REVIEW

**Comment by phillbaker** [comment]
@alambike thanks for the PR! Before merging we should get some test coverage around this behavior, it looks like the current usage in droplets/images/actions is also not covered, let me see if we can whip up something reusable.

**Comment by bobbytables** [comment]
Thanks for doing this!

**Comment by alambike** [comment]
You're welcome!! Hope that can be merged soon!

**Comment by phillbaker** [comment]
@alambike can you please rebase off of master and add specs similar to https://github.com/digitalocean/droplet_kit/pull/55/files#diff-2135438dbbe2f977854b95800e0bdc98 for these 6 endpoints?

The added specs should look similar to:
```
it_behaves_like 'a paginated index' do
   let(:fixture_path) { 'actions/all' }
   let(:api_path) { '/v2/actions' }
end
```

Thanks!

**Pull request closed without merging**
